services:
  - type: web
    name: sistema-academico
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn academic_sys.wsgi --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: academic_sys.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false # Usamos el valor configurado manualmente en el dashboard de Render
