# Generated by Django 5.2.12 on 2026-03-26 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Grado/Curso')),
                ('paralelo', models.CharField(max_length=5, verbose_name='Paralelo')),
            ],
            options={
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Año Lectivo')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Periodos Lectivos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.nivel')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.periodolectivo')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveIntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')])),
                ('descripcion', models.CharField(help_text='Ej: Tarea 1, Leccion 2', max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.curso')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.subject')),
                ('tipo_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.tipoinsumo')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lista', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.estudiante')),
            ],
            options={
                'ordering': ['numero_lista'],
                'unique_together': {('curso', 'numero_lista')},
            },
        ),
        migrations.CreateModel(
            name='Comportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveIntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')])),
                ('valor', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=1)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.actividad')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.matricula')),
            ],
        ),
    ]
