# Generated by Django 5.2.12 on 2026-03-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='trimestre',
        ),
        migrations.AddField(
            model_name='nota',
            name='trimestre',
            field=models.PositiveIntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')], default=1),
        ),
    ]
