# Generated by Django 5.2.12 on 2026-03-26 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_remove_actividad_trimestre_nota_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='subject',
        ),
        migrations.AddField(
            model_name='nota',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='grades.subject'),
            preserve_default=False,
        ),
    ]
