# Generated by Django 5.2.12 on 2026-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_remove_actividad_subject_nota_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='grades.subject'),
        ),
    ]
