# Generated by Django 5.2.12 on 2026-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_curso_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
