# Generated by Django 5.2.12 on 2026-03-29 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_nota_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tipo_insumo',
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Actividades'},
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='actividades',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='grades.actividad'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TipoInsumo',
        ),
    ]
