# Generated by Django 5.2.12 on 2026-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_cursoactividad_alter_curso_actividades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoactividad',
            options={'ordering': ['orden', 'pk'], 'verbose_name': 'Actividad por Curso', 'verbose_name_plural': 'Actividades por Curso'},
        ),
        migrations.AddField(
            model_name='cursoactividad',
            name='trimestre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
