# Generated by Django 5.2.12 on 2026-03-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_alter_cursoactividad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='actividad',
        ),
        migrations.AddField(
            model_name='cursoactividad',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.subject'),
        ),
        migrations.AddField(
            model_name='nota',
            name='curso_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.cursoactividad'),
        ),
        migrations.AlterField(
            model_name='cursoactividad',
            name='trimestre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')], default=1),
        ),
    ]
