# Generated by Django 5.2.12 on 2026-04-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_alter_comportamiento_trimestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comportamiento',
            name='trimestre',
            field=models.PositiveIntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')]),
        ),
        migrations.AlterField(
            model_name='cursoactividad',
            name='trimestre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')], default=1),
        ),
        migrations.AlterField(
            model_name='nota',
            name='trimestre',
            field=models.PositiveIntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')], default=1),
        ),
    ]
