# Generated by Django 5.2.12 on 2026-04-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0012_remove_periodolectivo_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['estudiante__apellidos', 'estudiante__nombres']},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='cedula',
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('curso', 'estudiante')},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='numero_lista',
        ),
    ]
