# Generated by Django 5.2.12 on 2026-04-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0013_alter_matricula_options_remove_estudiante_cedula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='orden',
        ),
    ]
