# Generated by Django 5.2.12 on 2026-04-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0015_alter_curso_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.nivel'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.periodolectivo'),
        ),
        migrations.AlterField(
            model_name='cursoactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.actividad'),
        ),
        migrations.AlterField(
            model_name='cursoactividad',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='grades.subject'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.estudiante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.subject'),
        ),
    ]
