# Generated by Django 5.2.12 on 2026-04-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_actividad_docente_estudiante_docente_nivel_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='docente',
        ),
    ]
